/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package recursoed_8210190_8210088.GUI;
import javax.swing.*;

import recursoed_8210190_8210088.Map;

import java.awt.event.ActionEvent;

public class App{
	JFrame f= new JFrame("Recurso ED - 8210088 - 8210190");
	JButton btn_jogadores = new JButton("Gestão de Jogadores");
	JButton btnLocais = new JButton("Gestão de Locais");
	JButton btnJogar=new JButton("Jogar");
	JButton btnSair=new JButton("Sair");

	Map map = new Map();

	public App(){
		JLabel l1;
		l1=new JLabel("Recurso ED - 8210088 - 8210190");
		l1.setBounds(150,50, 300,30);
		f.add(l1);

		btn_jogadores.setBounds(150,100,200,30);
		f.add(btn_jogadores);
        btn_jogadores.addActionListener(e -> gestaoJogadores(e));

		btnLocais.setBounds(150,150,200,30);
		f.add(btnLocais);
        btnLocais.addActionListener(e -> gestaoLocais(e));

		btnJogar.setBounds(150,200,200,30);
		f.add(btnJogar);
        btnJogar.addActionListener(e -> gestaoJogo(e));

		btnSair.setBounds(200,250,95,30);
		f.add(btnSair);
        btnSair.addActionListener(e -> closeProgram(e));


		f.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
		f.setSize(500,500);
		f.setLayout(null);
		f.setVisible(true);
	}

	private void gestaoJogadores(ActionEvent e) {
		new GestaoPlayers(map);
	}
	private void gestaoLocais(ActionEvent e) {
		new GestaoLocais(map);
	}
	private void gestaoJogo(ActionEvent e) {
		new Game(map);
	}
	private void closeProgram(ActionEvent e) {
		System.exit(0);
	}

	public static void main(String[] args) {

		new App();
	}
}
