/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package recursoed_8210190_8210088test;

import org.junit.Test;

import recursoed_8210190_8210088.GUI.App;

import static org.junit.Assert.*;

public class AppTest {
}
