/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package recursoed_8210190_8210088test;

import org.junit.Test;

import recursoed_8210190_8210088.App;

import static org.junit.Assert.*;

public class AppTest {
    @Test public void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }
}
